### ISSUE TITLE
Upgrading to 0.2.0 is failing on Linux

### ISSUE THREAD

**Issue by RahulKatariya** [Flight-School/AnyCodable#18]
I was upgrading to 0.2.0 and found that the deployment is failing on Linux due to CFNumberType.

I tried adding CoreFoundation import but it still fails with the reason nsnumber cannot be converted to cfnumber.

```swift
/tmp/app/.build/checkouts/AnyCodable/Sources/AnyCodable/AnyEncodable.swift:98:16: error: use of unresolved identifier 'CFNumberGetType'
                  switch CFNumberGetType(nsnumber) {
                         ^~~~~~~~~~~~~~~
   Failed to compile droplet: Failed to compile droplet: exit status 1
```

**Comment by mattt** [comment]
@RahulKatariya Sorry that this change is causing a problem on Linux. Can you tell me which distribution and Swift language version you're targeting? I haven't been able to reproduce this myself; CI builds are [passing](https://travis-ci.com/Flight-School/AnyCodable/builds/110156896) on Linux with Swift 5.0.1 and 4.1.2 Docker images.

**Comment by RahulKatariya** [comment]
@matt - I am using the following configuration.
```yml
sudo: required
dist: trusty
os: linux
language: generic
before_install:
  - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"
env: JOB=SWIFTPM
```

Here is the build output - https://www.travis-ci.org/RahulKatariya/AnyCodable/jobs/530857672.
